/* 
 * ztserver
 *
 * The ztserver REST API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISocketApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Creates a forwarding socket into the ZeroTier network
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket forward request</param>
        /// <returns>ZeroTierForwardedSocket</returns>
        ZeroTierForwardedSocket Forward (ZeroTierForwardRequest req);

        /// <summary>
        /// Creates a forwarding socket into the ZeroTier network
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket forward request</param>
        /// <returns>ApiResponse of ZeroTierForwardedSocket</returns>
        ApiResponse<ZeroTierForwardedSocket> ForwardWithHttpInfo (ZeroTierForwardRequest req);
        /// <summary>
        /// Removes a forwarding socket from the ZeroTier network
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket unforward request</param>
        /// <returns>ZeroTierOutcome</returns>
        ZeroTierOutcome Unforward (ZeroTierUnforwardRequest req);

        /// <summary>
        /// Removes a forwarding socket from the ZeroTier network
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket unforward request</param>
        /// <returns>ApiResponse of ZeroTierOutcome</returns>
        ApiResponse<ZeroTierOutcome> UnforwardWithHttpInfo (ZeroTierUnforwardRequest req);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Creates a forwarding socket into the ZeroTier network
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket forward request</param>
        /// <returns>Task of ZeroTierForwardedSocket</returns>
        System.Threading.Tasks.Task<ZeroTierForwardedSocket> ForwardAsync (ZeroTierForwardRequest req);

        /// <summary>
        /// Creates a forwarding socket into the ZeroTier network
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket forward request</param>
        /// <returns>Task of ApiResponse (ZeroTierForwardedSocket)</returns>
        System.Threading.Tasks.Task<ApiResponse<ZeroTierForwardedSocket>> ForwardAsyncWithHttpInfo (ZeroTierForwardRequest req);
        /// <summary>
        /// Removes a forwarding socket from the ZeroTier network
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket unforward request</param>
        /// <returns>Task of ZeroTierOutcome</returns>
        System.Threading.Tasks.Task<ZeroTierOutcome> UnforwardAsync (ZeroTierUnforwardRequest req);

        /// <summary>
        /// Removes a forwarding socket from the ZeroTier network
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket unforward request</param>
        /// <returns>Task of ApiResponse (ZeroTierOutcome)</returns>
        System.Threading.Tasks.Task<ApiResponse<ZeroTierOutcome>> UnforwardAsyncWithHttpInfo (ZeroTierUnforwardRequest req);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SocketApi : ISocketApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SocketApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SocketApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SocketApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SocketApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Creates a forwarding socket into the ZeroTier network 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket forward request</param>
        /// <returns>ZeroTierForwardedSocket</returns>
        public ZeroTierForwardedSocket Forward (ZeroTierForwardRequest req)
        {
             ApiResponse<ZeroTierForwardedSocket> localVarResponse = ForwardWithHttpInfo(req);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a forwarding socket into the ZeroTier network 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket forward request</param>
        /// <returns>ApiResponse of ZeroTierForwardedSocket</returns>
        public ApiResponse< ZeroTierForwardedSocket > ForwardWithHttpInfo (ZeroTierForwardRequest req)
        {
            // verify the required parameter 'req' is set
            if (req == null)
                throw new ApiException(400, "Missing required parameter 'req' when calling SocketApi->Forward");

            var localVarPath = "/forward";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (req != null && req.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(req); // http body (model) parameter
            }
            else
            {
                localVarPostBody = req; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Forward", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ZeroTierForwardedSocket>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ZeroTierForwardedSocket) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ZeroTierForwardedSocket)));
        }

        /// <summary>
        /// Creates a forwarding socket into the ZeroTier network 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket forward request</param>
        /// <returns>Task of ZeroTierForwardedSocket</returns>
        public async System.Threading.Tasks.Task<ZeroTierForwardedSocket> ForwardAsync (ZeroTierForwardRequest req)
        {
             ApiResponse<ZeroTierForwardedSocket> localVarResponse = await ForwardAsyncWithHttpInfo(req);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creates a forwarding socket into the ZeroTier network 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket forward request</param>
        /// <returns>Task of ApiResponse (ZeroTierForwardedSocket)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ZeroTierForwardedSocket>> ForwardAsyncWithHttpInfo (ZeroTierForwardRequest req)
        {
            // verify the required parameter 'req' is set
            if (req == null)
                throw new ApiException(400, "Missing required parameter 'req' when calling SocketApi->Forward");

            var localVarPath = "/forward";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (req != null && req.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(req); // http body (model) parameter
            }
            else
            {
                localVarPostBody = req; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Forward", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ZeroTierForwardedSocket>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ZeroTierForwardedSocket) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ZeroTierForwardedSocket)));
        }

        /// <summary>
        /// Removes a forwarding socket from the ZeroTier network 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket unforward request</param>
        /// <returns>ZeroTierOutcome</returns>
        public ZeroTierOutcome Unforward (ZeroTierUnforwardRequest req)
        {
             ApiResponse<ZeroTierOutcome> localVarResponse = UnforwardWithHttpInfo(req);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Removes a forwarding socket from the ZeroTier network 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket unforward request</param>
        /// <returns>ApiResponse of ZeroTierOutcome</returns>
        public ApiResponse< ZeroTierOutcome > UnforwardWithHttpInfo (ZeroTierUnforwardRequest req)
        {
            // verify the required parameter 'req' is set
            if (req == null)
                throw new ApiException(400, "Missing required parameter 'req' when calling SocketApi->Unforward");

            var localVarPath = "/unforward";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (req != null && req.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(req); // http body (model) parameter
            }
            else
            {
                localVarPostBody = req; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Unforward", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ZeroTierOutcome>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ZeroTierOutcome) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ZeroTierOutcome)));
        }

        /// <summary>
        /// Removes a forwarding socket from the ZeroTier network 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket unforward request</param>
        /// <returns>Task of ZeroTierOutcome</returns>
        public async System.Threading.Tasks.Task<ZeroTierOutcome> UnforwardAsync (ZeroTierUnforwardRequest req)
        {
             ApiResponse<ZeroTierOutcome> localVarResponse = await UnforwardAsyncWithHttpInfo(req);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Removes a forwarding socket from the ZeroTier network 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="req">Socket unforward request</param>
        /// <returns>Task of ApiResponse (ZeroTierOutcome)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ZeroTierOutcome>> UnforwardAsyncWithHttpInfo (ZeroTierUnforwardRequest req)
        {
            // verify the required parameter 'req' is set
            if (req == null)
                throw new ApiException(400, "Missing required parameter 'req' when calling SocketApi->Unforward");

            var localVarPath = "/unforward";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (req != null && req.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(req); // http body (model) parameter
            }
            else
            {
                localVarPostBody = req; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Unforward", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ZeroTierOutcome>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ZeroTierOutcome) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ZeroTierOutcome)));
        }

    }
}
