/* 
 * ztserver
 *
 * The ztserver REST API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ZeroTierJoinRequest
    /// </summary>
    [DataContract]
    public partial class ZeroTierJoinRequest :  IEquatable<ZeroTierJoinRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ZeroTierJoinRequest" /> class.
        /// </summary>
        /// <param name="Nwid">Nwid.</param>
        /// <param name="Path">Path.</param>
        public ZeroTierJoinRequest(string Nwid = default(string), string Path = default(string))
        {
            this.Nwid = Nwid;
            this.Path = Path;
        }
        
        /// <summary>
        /// Gets or Sets Nwid
        /// </summary>
        [DataMember(Name="nwid", EmitDefaultValue=false)]
        public string Nwid { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name="path", EmitDefaultValue=false)]
        public string Path { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ZeroTierJoinRequest {\n");
            sb.Append("  Nwid: ").Append(Nwid).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ZeroTierJoinRequest);
        }

        /// <summary>
        /// Returns true if ZeroTierJoinRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ZeroTierJoinRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ZeroTierJoinRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Nwid == other.Nwid ||
                    this.Nwid != null &&
                    this.Nwid.Equals(other.Nwid)
                ) && 
                (
                    this.Path == other.Path ||
                    this.Path != null &&
                    this.Path.Equals(other.Path)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Nwid != null)
                    hash = hash * 59 + this.Nwid.GetHashCode();
                if (this.Path != null)
                    hash = hash * 59 + this.Path.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
